### ISSUE TITLE
Home Assistant Core 2022.3 had some breaking changes

### ISSUE THREAD

**Issue by rclark213** [neggert/hass-egauge#118]
## Version of the custom_component

0.4.0

## Configuration

```yaml
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 4:05:14 PM (3 occurrences)
Last logged: 4:05:19 PM

Unable to install package egauge-async==0.1.1: ERROR: Cannot install egauge-async==0.1.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Logger: homeassistant.setup
Source: setup.py:155
First occurred: 4:05:19 PM (1 occurrences)
Last logged: 4:05:19 PM

Setup failed for egauge: Requirements for egauge not found: ['egauge-async==0.1.1'].
```
Not sure where else I should be looking for helpful logs. 

## Describe the bug

After upgrading to Home Assistant Core 2022.3, the error logs above showed up. Additionally, all eGauge sensors are now showing as "unavailable". 

## Debug log

```text

Add your logs here.

```
